/** Cross-platform publisher. Run only from a clean task branch containing reviewed commits. */
import {spawnSync} from 'node:child_process';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
const run=(bin,args,opts={})=>{const r=spawnSync(bin,args,{encoding:'utf8',...opts});if(r.status!==0)throw Error(`${bin} ${args.slice(0,3).join(' ')} failed:\n${r.stderr||r.stdout||r.error}`);return r.stdout.trim();};
const gh=(...args)=>run('gh',args);const git=(...args)=>run('git',args);const delay=ms=>new Promise(r=>setTimeout(r,ms));const hub='zcxxcz/zcxxcz.github.io';
async function waitRun(repo,sha,event){for(let i=0;i<120;i++){const rows=JSON.parse(gh('run','list','-R',repo,'--workflow','pages.yml','--commit',sha,'--event',event,'--limit','10','--json','databaseId,status,conclusion,url'));const r=rows[0];if(r?.status==='completed'){if(r.conclusion!=='success')throw Error(`Publish checks failed: ${r.url} (${r.conclusion})`);return r;}if(i%6===0)console.log(`Waiting for ${event} (${repo}, ${sha.slice(0,7)})…`);await delay(10000);}throw Error(`Timed out; inspect https://github.com/${repo}/actions`);}
async function publishCurrent(){const repo=JSON.parse(gh('repo','view','--json','nameWithOwner')).nameWithOwner;const branch=git('branch','--show-current');if(!branch||branch==='main')throw Error('Use a task branch, not main or detached HEAD.');if(git('status','--porcelain'))throw Error('Commit only the intended task files first; working tree must be clean.');git('fetch','origin','main');try{git('merge-base','--is-ancestor','origin/main','HEAD');}catch{throw Error('main has moved. Merge origin/main into your branch, resolve conflicts, rerun checks, and retry.');}const sha=git('rev-parse','HEAD');git('push','-u','origin',branch);let prs=JSON.parse(gh('pr','list','--head',branch,'--state','open','--json','number,url'));if(!prs.length){gh('pr','create','--base','main','--head',branch,'--title',git('log','-1','--format=%s'),'--body','Publish the committed content and deployment changes after the Publish Pages checks succeed.');prs=JSON.parse(gh('pr','list','--head',branch,'--state','open','--json','number,url'));}const pr=prs[0];console.log(`Pull request: ${pr.url}`);await waitRun(repo,sha,'pull_request');gh('pr','merge',String(pr.number),'--squash','--match-head-commit',sha);const merged=JSON.parse(gh('pr','view',String(pr.number),'--json','mergeCommit')).mergeCommit.oid;await waitRun(repo,merged,'push');console.log(`Published ${repo} at ${merged}`);return repo;}
async function refresh(){const marker='publish-'+Date.now();gh('workflow','run','pages.yml','-R',hub,'-f',`request_id=${marker}`);for(let i=0;i<120;i++){const rows=JSON.parse(gh('run','list','-R',hub,'--workflow','pages.yml','--event','workflow_dispatch','--limit','30','--json','status,conclusion,url,displayTitle'));const row=rows.find(r=>r.displayTitle===marker);if(row?.status==='completed'){if(row.conclusion!=='success')throw Error(`Index refresh failed: ${row.url}`);const resp=await fetch('https://zcxxcz.github.io/build-report.json');if(!resp.ok)throw Error('Published index is not accessible');const report=await resp.json();if(report.warnings?.length)throw Error('Published with stale sources: '+report.warnings.join('; '));console.log('Index refreshed: https://zcxxcz.github.io/');return;}await delay(10000);}throw Error('Index refresh timed out');}
async function register(repo){let cfg;try{cfg=JSON.parse(await readFile('publish.json','utf8'));}catch{throw Error('Independent sites need publish.json before registration.');}const id=repo.split('/')[1];const temp=await mkdtemp(path.join(os.tmpdir(),'content-hub-'));const original=process.cwd();try{run('gh',['repo','clone',hub,temp,'--','--depth','1']);process.chdir(temp);try{await readFile(`sites/${id}.json`);return;}catch{}git('switch','-c',`register/${id}-${Date.now()}`);await writeFile(`sites/${id}.json`,JSON.stringify({id,repository:repo,catalog:cfg.catalog},null,2)+'\n');git('add',`sites/${id}.json`);git('commit','-m',`Register ${id} in content index`);await publishCurrent();}finally{process.chdir(original);await rm(temp,{recursive:true,force:true});}}
try{if(process.argv.includes('--refresh-only')){await refresh();}else{const repo=await publishCurrent();if(repo!==hub){await register(repo);await refresh();}const url=repo===hub?'https://zcxxcz.github.io/':`https://zcxxcz.github.io/${repo.split('/')[1]}/`;const res=await fetch(url);if(!res.ok)throw Error(`Site returned ${res.status}: ${url}`);console.log('Live: '+url);}}catch(e){console.error(e.message);process.exitCode=1;}
